### PR TITLE
Improving demo

### PR DESCRIPTION
**Pull request by BastiaanOlij**
Still working on this one but making a slightly more complex demo.

The demo now includes a spectator view in which we render the players wands (and will also render the players glasses once we fix another issue).

The wands allow you to move around the balls held within the container.

image

Definately can be improved loads by making a nicer container and give the balls some textures so we can see them rolling around (or maybe make a nicer game, I'm thinking air hockey)

### CODE REVIEW

**Comment by patrickdown** [comment]
This looks cool. My only comment so far is maybe instead of hard coded paths to the viewport and origin node in the Glasses scene those nodes should be searched for? I don't know how variable a custom glasses scene might get.

**Comment by BastiaanOlij** [comment]
> This looks cool. My only comment so far is maybe instead of hard coded paths to the viewport and origin node in the Glasses scene those nodes should be searched for? I don't know how variable a custom glasses scene might get.

That is in part why we have the base scene to be extended, that guarantees certain paths. That said, I think this can be improved upon.

**Comment by BastiaanOlij** [comment]
@patrickdown I've added that you can use the wand as a pointer to pick up balls and added the ability to move around with the joystick. 

I'm not sure if this is the best type of example but it is showing a few things off. I need to fix some other things before I can add more.

I think this is worth merging as is and just keep building upon, Maybe add other things around that we can interact with.

**Comment by BastiaanOlij** [comment]
Just moved this back to draft, I think we need something much nicer for our start. The work Malcolm is doing will help loads.

**Comment by BastiaanOlij** [comment]
I'm closing this pull request, it's outdated and we have better demos now as part of the toolkit.

**Pull request closed without merging**
